# Our custom ZMK status screen
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# LVGL image support for Scuba Cat
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_IMG=y

# Keep display processing separate from keyboard/BLE work
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2560
