# Disable nice_oled's own widget/status implementation.
CONFIG_NICE_OLED_WIDGET_STATUS=n

# Our Scuba Cat screen.
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# LVGL image support.
CONFIG_LV_USE_IMG=y

# Keep display work away from normal keyboard/BLE work.
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2560
